name: Docker

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

env:
  REGISTRY_USERNAME: binoculars
  REGISTRY_URI: ghcr.io

jobs:
  push:
    runs-on: ubuntu-latest
    if: github.event_name == 'push'

    steps:
      - uses: actions/checkout@v2.4.0

      # - name: Login to GitHub Container Registry
      #   uses: docker/login-action@v1.12.0
      #   with:
      #     registry: ghcr.io
      #     username: quipt-devsecops
      #     password: ${{ secrets.CR_PAT }}

      - name: Build and push image
        run: |
          NAMED_TAG=$(printf "${{ github.ref }}" | sed -e 's|^refs/||' -e 's|^heads|branch|' -e 's|^tags|tag|' -e 's|/|_|')
          COMMIT_TAG=commit_${{ github.sha }}

          docker build .